kind: pipeline
name: sample-drone-pipeline

steps:
- name: build
  image: microsoft/dotnet
  commands:
  - dotnet build ./sample-app/

- name: infrastructure
  image: remkoseelig/terraform-azure-cli
  environment:
    azusername:
      from_secret: azusername
    azpassword:
      from_secret: azpassword
  commands:
  - az login --service-principal --username $azusername --password $azpassword --tenant 2076a2b7-809d-4f17-b222-d88effb0cefb
  - terraform init "./terraform"
  - terraform apply -auto-approve -var ARM_CLIENT_ID=%ARM_CLIENT_ID% -var ARM_CLIENT_SECRET=%ARM_CLIENT_SECRET% -var ARM_SUBSCRIPTION_ID=%ARM_SUBSCRIPTION_ID% "./terraform"
